### ISSUE TITLE
Tạo màn hình bắt đầu cho game

### ISSUE THREAD

**Issue by sprBbe** [tridung240400/MathGame#1]
Màn hình bắt đầu có 4 nút chọn để đi vào các trò chơi riêng biệt.

**Comment by tridung240400** [comment]
Đã hoàn thành ở commit "Thêm màn hình bắt đầu cho game"
https://github.com/tridung240400/MathGame/commit/562dd4b6374c00feb2f9ed27d19756ec3781b67c
